export interface PlAgingReport {
    user_name: string, 
    env: string, 
	uploadedStartDate: string,
	uploadedEndDate: string,
	initialStartDate: string,
	initialEndDate: string,
	approveReceiptStartDate: string,
	approveReceiptEndDate: string,
	poGeneratedStartDate: string,
	poGeneratedEndDate: string,
    page: number, 
    pageSize: number, 
    search: string | null, 
    sortColum: string, 
    sortOrder: string,
    filterModel: string | null, 
}

export interface PlAgingReportStatus {
    user_name: string,
    env: string, 
	uploadedStartDate: string,
	uploadedEndDate: string,
	initialStartDate: string,
	initialEndDate: string,
	approveReceiptStartDate: string,
	approveReceiptEndDate: string,
	poGeneratedStartDate: string,
	poGeneratedEndDate: string,
    search: string | null, 
    sortColum: string, 
    sortOrder: string,
    filterModel: string | null, 
}
